#
# DSOMM showcase with data stored on mysql,
#   processed by graphql
#   and presented via a react application.
#
version: '3.6'
services:
  db:
    image: mysql:8.0.21
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
  gql: &gql
    depends_on:
      - db
      - test
    build: .
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_HOST: db
      PYTHONPATH: ":/code:"
    ports:
    - 13001:8000
    volumes:
      - .:/code
    working_dir: /code
  dev:
    <<: *gql
    depends_on:
    - db
    ports: []
    command: ["/usr/bin/tail", "-f", "/etc/hosts"]
  web:
    build: ./webapp
    ports:
    - 13000:3000
    depends_on:
    - gql
  test:
    <<: *gql
    depends_on:
    - db
    ports: []
    command: ["tox"]
volumes:
  db_data:
